version: "3"
services:
  api:
    build: ./api
    container_name: api
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
  feedbot:
    image: dash2507/feedbot
    container_name: feedbot
    ports:
      - 80:80